#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustwallpaper /usr/bin/rustwallpaper

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustwallpaper.service ]; then
			rm /etc/systemd/system/rustwallpaper.service /usr/lib/systemd/system/rustwallpaper.service /usr/lib/systemd/user/rustwallpaper.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/rustwallpaper.service /usr/lib/systemd/system/rustwallpaper.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustwallpaper.service: Unit rustwallpaper.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustwallpaper.service:10: Executable path is not absolute: pkill -f "rustwallpaper --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustwallpaper.service
		fi
		systemctl daemon-reload
		systemctl enable rustwallpaper
		systemctl start rustwallpaper
	fi
fi
