#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/rustwallpaper /usr/bin/RustWallpaper

		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop rustwallpaper || true
			systemctl disable rustwallpaper || true
			rm /etc/systemd/system/rustwallpaper.service /usr/lib/systemd/system/rustwallpaper.service || true

			# also clean up the legacy `rustdesk` unit shipped by older builds
			systemctl stop rustdesk >/dev/null 2>&1 || true
			systemctl disable rustdesk >/dev/null 2>&1 || true
			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service || true

			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'rustwallpaper +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop rustwallpaper >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/rustwallpaper.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
